apiVersion: v1
kind: Pod
metadata:
  name: sa-tester
  namespace: rbac-lab
spec:
  serviceAccountName: lector-pods
  containers:
    - name: tester
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
  restartPolicy: Never
