apiVersion: v1
kind: ServiceAccount
metadata:
  name: lector-pods
  namespace: rbac-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leer-pods-binding
  namespace: rbac-lab
subjects:
  - kind: ServiceAccount
    name: lector-pods
    namespace: rbac-lab
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
