apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
  tolerations:
    - key: "acceso"
      operator: "Equal"
      value: "bloqueado"
      effect: "NoSchedule"
  nodeSelector:
    rol: worker2
